- benches/dot_product_benchmark.rs
- src/models/common.rs
- src/models/dot_product.rs
- src/models/dot_product/arm64.rs
- src/models/dot_product/x86_64.rs
- Separate ARM and x86 implementations and allow the project to build on ARM platforms.
- Looked into Neon ISA and what is portable/available across all ARM platforms.
- Implement the dot product with multiply-add for Neon. 
- Common and benchmark examples haven't been implemented.
> feat: start adding support for aarch64/arm NEON

- README.md
- config.toml
- src/config_loader.rs
- src/web_server.rs
The default continues to be https. Http mode is primarily meant for local development. But it could also be useful if the db is behind a reverse proxy that takes care of SSL. 
Besides the main change, this PR also includes a commit to load TLS config (paths to the certificate files) from `config.toml` file instead of an env var.
> Add optional support for http mode (w/o TLS)

- org/graph-datalog.org
adding a non-decomposable ternary relationship definition in the DSL spec
- thought would be useful given we've these in examples later on
> ternary relationship example added in DSL spec

- Cargo.toml
- benches/inverted_index_benchmark.rs
Create a criterion benchmark for testing performance of inverted index using randomly generated sparse vectors https://github.com/cosdata/cosdata/issues/88.
To run the benchmark, navigate to the `benches` folder and run `cargo bench --bench inverted_index_benchmark`.
> Create inverted index criterion benchmark

- benches/inverted_index_benchmark.rs
Enhance the `inverted_index_benchmark` test.
- Add seeding for deterministic tests
- Use Criterion's `bench_with_input` method
> Enhance perf test for inverted index

- Cargo.lock
- Cargo.toml
- benches/inverted_index_benchmark.rs
- src/bin/inverted_index_main_flame.rs
- src/models/lazy_load.rs
- src/models/types.rs
- src/storage/inverted_index.rs
On benchmarking the current implementation we found the following problems -
* Heavy contention on loops that for writing data into `ArcShift` for adding new children to inverted index
* Copying of huge amount of memory for writing dimension values into data field of inverted index item
---
The first problem has been solved by using `rcu_project` present in the latest `arcshift` release. It allows us to conditionally update the value and project something from the underlying value. This allows us to transactionally update and read from the arcshift data. It is ideal for `create_or_insert` child function needed to traverse the inverted index dag. These are the key properties -
1. Maybe update
1. if a child exists don't add anything
2. if it doesn't exists try to add a new default child
2. …
> Reduce contention on inserting children into `InvertedIndexItem`

- benches/inverted_index_benchmark.rs
- src/bin/inverted_index_main_flame.rs
- src/models/types.rs
- src/storage/inverted_index.rs
- Modify inverted index benchmark to insert `(dimension, value)` pairs for non-zero indices, instead of `Vec<f32>`
- Create new `SparseVector` datatype. Change `InvertedIndex::add_sparse_vector()` to directly process `SparseVector`
> Modify benchmark to insert (dim, val) pairs

- src/models/buffered_io.rs
Also includes 
- Unit tests for the `seek_with_cursor` method and related fixes
- Fix for handling the case of `write_with_cursor` writing past EOF
> Property based tests for buffer_io module

- src/models/cache_loader.rs
- src/models/serializer/eager_lazy_item.rs
- src/models/serializer/eager_lazy_item_set.rs
- src/models/serializer/lazy_item.rs
- src/models/serializer/lazy_item_map.rs
- src/models/serializer/lazy_item_set.rs
- src/models/serializer/lazy_item_vec.rs
Used an enum to allow `InvertedIndexItem<Storage>` and `MergedNode` to be cached, other types can also be easily added when needed
> feat: make cache more generic

- src/models/lazy_load.rs
- src/models/serializer/incremental_serializable_growable_data.rs
- src/models/serializer/mod.rs
- src/models/serializer/new_struct.rs
Create an incrementally serializable, growable collection.
The collection must support `apppend()` and `read_all()` and must be serializable incrementally.
> Create incrementally serializable growable collection

- src/api_service.rs
don't panic when `prev` node is `Invalid`
> fix(api_service/init_vector_store): prevent panic

- Cargo.lock
- Cargo.toml
- benches/inverted_index_benchmark.rs
Implement a more robust test suite, with more configuration parameters and deterministic test data generation.
- Use `ChaCha8Rng` for random vector generation
- Add parameters for min/max nonzero dimensions and RNG seed
> Add parameters for deterministic rng

- .github/workflows/ci.yml
- Add new `format` job to CI workflow
- Check formatting in `src/` and `benches`/ directories by running `cargo fmt --all -- --check src/ benches/`
- Provide error message if formatting check fails: 
```
Formatting check failed!
Please run this command before committing:
cargo fmt --all -- src/ benches/
```
> chore(ci): add cargo fmt check to CI

- src/indexes/helpers.rs
Before it was taking `O(logn)` time to get the exponent of 4 less than equal to the value
As we know the the value cannot exceed `u32`, we can pre-compute the powers of 4 in which the index  of the pre-computed array will be the exponents..
So, as the size of the pre-computed array is fixed, the time complexity is reduced to `O(1)`.
> Optimize largest power of 4 computation

- .cargo/config.toml
- .github/workflows/release.yml
- Runs only after successful completion of "CI" on main
- Prepares a statically linked binary (using musl libc) and uploads it as a release. Also default `config.toml` is added to the release
- Short SHA of the latest HEAD is appended to the release
> Release Action to publish binary

- src/distance/cosine.rs
- src/models/serializer/hnsw/tests.rs
- src/models/serializer/storage.rs
- src/models/serializer/tests.rs
- src/quantization/scalar.rs
- src/storage/mod.rs
compute square root at the time of quantization instead of distance calculation for `UnsignedByte`
> fix(quantization/scalar): compute sqrt at the time of quantization

- src/api_service.rs
- src/indexes/hnsw/mod.rs
- src/models/common.rs
- src/models/versioning.rs
- src/vector_store.rs
This PR continues from #258 and addresses issues in the upsert API's indexing behavior.  
- **Fixed indexing behavior in the upsert API (outside transaction):** The intended behavior—where vectors are collected, serialized, and indexed only after reaching a threshold (configured in `config.toml`)—was not working as expected. Previously, indexing calls occurred before the threshold was met. This fix ensures proper batching before indexing.  
- **Ensured consistent use of the `key!` macro for LMDB operations** (contributed by @naiquevin) to prevent key collisions.
- **Miscellaneous minor fixes and improvements.**
> Fix dense index upsert

- src/api/vectordb/vectors/controller.rs
- src/api/vectordb/vectors/repo.rs
- src/api_service.rs
- src/distance/cosine.rs
- src/distance/dotproduct.rs
- src/distance/euclidean.rs
- src/distance/hamming.rs
- src/distance/mod.rs
- src/grpc/vectors/mod.rs
- src/indexes/hnsw/types.rs
- src/metadata/mod.rs
- src/metadata/query_filtering.rs
- src/metadata/schema.rs
- src/models/common.rs
- src/models/embedding_persist.rs
- src/models/types.rs
- src/vector_store.rs
- tests/test_metadata_filters.py
The metadata filtering functionality returns false negatives. To fix it, we're now using the pseudo nodes approach plus a bunch of other changes that deviate from the org document (yet to be updated). This PR includes all those changes but note that the false negatives are not fixed yet because pseudo nodes are not getting indexed correctly. 
This is because the vector ids are of type u64 but the neighbor ids have type u32.  This usually doesn't affect regular vectors inserted by the user. However, the the root node has id = u64::MAX and the pseudo node has id =  2^56-1, so casting them to u32 truncates them to the same value 4294967294 and the `skipm` membership check always returns true in `traverse_find_nearest`.  This is yet to be thought through and fixed. 
The PR is backward …
> Metadata filtering fixes 2

- src/metadata/query_filtering.rs
- src/metadata/schema.rs
This method is to be used for calculating the no. of ids that should be allocated for the replica set of a vector that's inserted in a collection. 
The PR also includes a couple of more commits: 
1. Got rid of the replica for the combination of all fields. It's not required with the new logic where we have separate replicas for matching individual fields and OR conditions (unless there's an AND condition for all fields). 
2. The Vec<SupportedCondition> is deduplicated when initializing MetadataSchema instance. This is because the method to calculate no. of max replicas depends on the length of this vector.
> Add `max_num_replicas` method in MetadataSchema

- Cargo.lock
- Cargo.toml
- org/src/viewer.rs
- src/indexes/hnsw/mod.rs
- src/models/cache_loader.rs
- src/models/common.rs
- src/models/file_persist.rs
- src/models/lru_cache.rs
- src/models/prob_lazy_load/lazy_item.rs
- src/models/prob_node.rs
- src/models/serializer/hnsw/lazy_item.rs
- src/models/serializer/hnsw/lazy_item_array.rs
- src/models/serializer/hnsw/neighbors.rs
- src/models/serializer/hnsw/node.rs
- src/models/serializer/hnsw/tests.rs
- src/models/serializer/inverted/lazy_item.rs
- src/models/serializer/tf_idf/lazy_item.rs
- src/vector_store.rs
This PR fixes HNSW index nodes versioning by getting rid of per node version tree and directly storing latest version pointer in the base version.
> Fix HNSW node versioning

- src/models/collection.rs
- src/models/serializer/quotients_map.rs
- src/models/serializer/tests.rs
- src/models/serializer/tree_map.rs
- src/models/tree_map.rs
This PR modifies the `TreeMap` to not store the original key.
> fix(tree_map): do not store original key

- src/vector_store.rs
It seems this code was mistakenly removed during a recent refactor (commit - 31e2db3504ceece184ddac103b3cab831b12dc7e).
Additionally, this commit fixes a typo in a variable name 'overrideen' -> 'overridden'.
If the vector store has metadata schema, the max_level is overridden for pseudo nodes. Looks like this code was mistakenly removed in a recent refactor. This commit adds it back.
Creating a separate PR so it's easier to review. 
Fixes #
@a-rustacean @tinkn Could you please review this when you have a moment? Thank you!
> Fix max_level calculation for pseudo nodes during indexing

- install/install.sh
This is a feature PR as mentioned in https://github.com/cosdata/cosdata/issues/301 and improves shell configuration portability by automatically detecting the user's current shell (`bash`, `zsh`, or `fish`) and appending the necessary `export PATH` and `COSDATA_HOME` lines to the correct shell configuration file (`~/.bashrc`, `~/.zshrc`, or `~/.config/fish/config.fish`). This ensures seamless setup across different environments and simplifies user instructions.
@anandwana001  Could you please review this when you have a moment? Thank you!
> feat(install): add shell detection for PATH and COSDATA_HOME setup

- src/models/serializer/quotients_map.rs
- src/models/serializer/tf_idf/term.rs
- src/models/serializer/tf_idf/tests.rs
- src/models/serializer/versioned_item.rs
- src/models/serializer/versioned_vec.rs
- src/models/sparse_ann_query.rs
- src/models/tf_idf_index.rs
- src/models/tree_map.rs
This PR fixes potential segfaults in the `UnsafeVersionedItem` and `UnsafeVersionedVec` data structures, also renaming them to `VersionedItem` and `VersionedVec` respectively, indicating that these structures are safe.
> Fix potential segfault in unsafe data structures

- src/api/vectordb/vectors/repo.rs
- src/api_service.rs
- src/distance/cosine.rs
- src/grpc/vectors/mod.rs
- src/indexes/hnsw/mod.rs
- src/indexes/inverted/mod.rs
- src/indexes/mod.rs
- src/metadata/mod.rs
- src/metadata/schema.rs
- src/models/collection.rs
- src/models/common.rs
- src/models/file_persist.rs
- src/models/prob_node.rs
- src/models/types.rs
- src/vector_store.rs
- tests/test_metadata_filters.py
WIP: This PR is not ready to be merged yet. Opening a PR for @a-rustacean to review. There's one issue which I am debugging with his help. 
This PR introduces another kind of root node in the HNSW index besides the original one (henceforth it's referred to as `main root node`). The new one is called `pseudo root node` and all metadata replica nodes will be created under the pseudo root node. The base nodes will be created under main root node. 
My deterministic tests are passing 100% - by deterministic tests I mean the search query vector is exactly the same as a previously inserted vector along with known metadata filters.
However, if the server is restarted after adding data, it crashes at the time of deserializing the prob node in the load_hnsw_index function call. I am debugging this. …
> Use separate root nodes in hnsw index for metadata filtering

- src/models/prob_node.rs
This PR fixes a segfault in the HNSW index, by fixing the locking of node's neighbors.
> fix(hnsw/node): take write lock when updating neighbors
