cosdata/cosdata

src/api/vectordb/mod.rs, src/api/vectordb/transactions/abort.rs, src/api/vectordb/transactions/commit.rs, src/api/vectordb/transactions/create.rs, src/api/vectordb/transactions/delete.rs, src/api/vectordb/transactions/mod.rs, src/api/vectordb/transactions/update.rs, src/api/vectordb/transactions/upsert.rs, src/api/vectordb/upsert.rs, src/api_service.rs, src/models/types.rs, src/web_server.rs
=> feat: transaction

org/buffered_file_io.org, src/models/buffered_io.rs, src/models/lru_cache.rs, src/models/mod.rs
Based on [org/buffered_file_io.org]
=> Buffered file IO along with LRUCache implementation

.gitignore, src/api/vectordb/create.rs, src/api_service.rs, src/models/rpc.rs
modified the response structure for this endpoint 
to return data about the created vector store
=> Create collection api

Cargo.lock, Cargo.toml, src/api/auth/authentication_middleware.rs, src/api/auth/controller.rs, src/api/auth/dtos.rs, src/api/auth/error.rs, src/api/auth/get_token.rs, src/api/auth/mod.rs, src/api/auth/service.rs, src/web_server.rs, test.py
- created authentication module, controller, service, middleware
- protected all endpoints with bearer auth except the `auth/login`
=> Authentication RESTful api module

src/api_service.rs, src/models/file_persist.rs, src/models/lazy_load.rs, src/models/serializer/tests.rs, src/vector_store.rs
- Rename `get_data` to `get_lazy_data`
- Add `get_data` method which panics on error
- Add `try_get_data` method which returns a `Result`
=> Update methods on `LazyItem`

Cargo.toml, benches/lazy_item_benchmark.rs, src/storage/inverted_index.rs
This PR contains benchmark for LazyItemVec, LazyItemMap during Retrieval and Insertions.
=> LazyItemVec and Map Benchmark

src/models/cache_loader.rs, src/models/serializer/dashmap.rs, src/models/serializer/inverted_index.rs, src/models/serializer/inverted_index_item.rs, src/models/serializer/mod.rs, src/models/serializer/storage.rs, src/models/serializer/tests.rs, src/storage/inverted_index.rs
=> Implement `CustomSerialize` for `InvertedIndex`

src/models/serializer/tests.rs
=> chore: add (de)serialization tests for `LazyItemVec`

org/lmdb.org, src/api/vectordb/collections/controller.rs, src/api/vectordb/collections/repo.rs, src/api/vectordb/collections/service.rs, src/api/vectordb/upsert.rs, src/api/vectordb/vectors/controller.rs, src/api/vectordb/vectors/error.rs, src/api/vectordb/vectors/repo.rs, src/api/vectordb/vectors/service.rs, src/api_service.rs, src/app_context.rs, src/main.rs, src/models/cache_loader.rs, src/models/lazy_load.rs, src/storage/inverted_index_old.rs, src/vector_store.rs, src/web_server.rs, test.py
NOTE: Opening a PR for early feedback. Planning to push more commits. Please don't merge yet. 
- Refactor to add node registry and buffer managers to actix app state
- Lazy-load vectors from disk if required at the time of indexing.
=> Refactor to initialize application context and fix lazy loading of merge nodes

src/api/vectordb/upsert.rs
=> error handling

org/src/project_to_dim.rs
1 - I optimized the standard_deviation function by using Welford’s method to calculate the mean and variance in a single pass through the data, reducing redundant iterations.
2 - This approach improves performance by halving the number of passes required, and it enhances numerical stability, yielding accurate results even with very large or very small values.
=> Optimizing Standard Deviation using Welford's Method

org/api-doc.org
- added `get collections` endpoint 
- added `delete collection` endpoint
- updated `transaction creation` response format
- updated `create vector in a transaction` request body 
- updated `upsert vectors in a transaction` request body
- updated `vector basic search` request body
- updated `create index params`
- added all endpoints of `vector lifecycle`
- updated error format
=> Api doc org file

src/models/lru_cache.rs
This is to extend or customize the behavior of the cache at the time of eviction by passing a callback function. The function will be called just before an entry is evicted from the cache and with shared reference to the value being evicted as the arg.
=> Implement evict_hook in LRUCache

.github/workflows/ci.yml
As mentioned in the issue #187 
This PR introduces clippy linting job using `cargo hack` tool
=> Setup Clippy Linting Job

.gitignore, test_multiple_datasets.py
This file tests multiple datasets from hugging face, calculates its brute forced similarities and compares it against the server. The cli takes care of downloading the parquet files.
Used polars insead of pandas due to memory constrains and faster execution times.
=> Test file for multiple datasets from HF.

org/api-doc.org
Update API Specification Documentation
- Fixed endpoint paths to match actual implementation
- Updated request/response formats per current code
- Added missing error codes and corrected HTTP status codes
- Documented configuration options from config.toml
- Corrected transaction ID and vector ID types (uint32, uint64)
- Added RPC response type information
- Fixed content-type headers for error responses
=> docs: update API to match implementation

org/metadata_filtering_hnsw.org
This is based on the call and discussion in the discord thread https://discord.com/channels/1250672673856421938/1335809236537446452
=> Update the doc about metadata filtering in HNSW index

org/api-doc.org
- Add scalar quantization example with data types
- Update HNSW parameters
- Reorganize sections
=> docs: update index creation examples and reorganize sections

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, build.rs, config.toml, proto/vector_service.proto, src/api/vectordb/vectors/error.rs, src/app_context.rs, src/grpc/collections/mod.rs, src/grpc/error.rs, src/grpc/mod.rs, src/grpc/server.rs, src/grpc/vectors/mod.rs, src/grpc/vectors/test.rs, src/main.rs, src/models/common.rs, test-grpc.py
Add gRPC support for Collections service
-     Set up gRPC server alongside HTTP(concurrently)
-     Add proto definitions
-     Implement Collections operations
-     Use existing CollectionsMap public methods
-     Added grpc test
=> grpc implementation and grpc test client

src/grpc/vectors/mod.rs, src/main.rs, src/web_server.rs
Fixes a panic introduced by the gRPC server changes merged in PR #221
=> Fix: actix-rt panic introduced in #221 (gRPC server changes)

src/main.rs, src/web_server.rs
use `Data<AppContext>` for app data instead of `Data<Arc<AppContext>>`
=> fix(web_server): fix 500 error

config.toml, org/src/viewer.rs, src/api_service.rs, src/config_loader.rs, src/models/buffered_io.rs, src/models/embedding_persist.rs, src/models/lazy_load.rs, src/models/meta_persist.rs, src/models/serializer/prob/lazy_item_array.rs, src/models/serializer/prob/neighbors.rs, src/models/serializer/prob/node.rs, src/models/serializer/prob/tests.rs, src/models/serializer/tests.rs, src/models/types.rs, src/storage/inverted_index_old.rs, src/storage/inverted_index_sparse_ann.rs, src/storage/inverted_index_sparse_ann_basic.rs, src/storage/inverted_index_sparse_ann_new_ds.rs
- remove eager flush
- fix root version deserialization
- persist values range & sample threshold
=> fixes/follow ups from #220

org/metadata_filtering_hnsw.org, src/api/vectordb/collections/dtos.rs, src/api/vectordb/collections/repo.rs, src/api_service.rs, src/grpc/collections/mod.rs, src/lib.rs, src/main.rs, src/metadata/de.rs, src/metadata/mod.rs, src/metadata/query_filtering.rs, src/metadata/schema.rs, src/models/collection.rs, src/models/common.rs
Opening` a PR for early review. It's WIP.
=> WIP metadata filtering

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, build.rs, rust-toolchain.toml, src/cfg_macros.rs, src/grpc/collections/mod.rs, src/grpc/mod.rs, src/grpc/vectors/mod.rs, src/lib.rs, src/main.rs
`grpc-server` is now an opt-in feature.
Also, `tokio` is now a `dev-dependency`. Should help slightly with compilation time.
=> chore: grpc-server as a feature

.github/workflows/ci.yml, load-test.py, rps-test.py, sparse-vector-test.py, src/args.rs, src/models/types.rs, test-dataset.py, test-query.py, test.py
1. Adds password confirmation when setting up for the first time
2. Replaces the hardcoded "admin" password with the admin key
3. Updates test scripts to prompt for password instead of using hardcoded credentials
=> Add admin key confirmation and replace hardcoded admin password

src/api_service.rs, src/vector_store.rs
The very first HTTP request to insert a vector using the `POST /collections/{collection_id}/vectors` endpoint would fail because the 'count_unindexed' key wouldn't be created yet in the `metadata` db in LMDB. This commit handles this by considering the default value of 0.
Steps to reproduce:
1. reset data by deleting the 'data' dir (backup if required)
2. create collection 
3. create dense index explicitly 
4. insert a vector - request fails with error `MDB_NOTFOUND: No matching key/data pair found`.
=> Handle case where 'count_unindexed' key is not yet created in lmdb

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Fixes #271 
1. Added bug report template
2. Added feature request template
3. Added config for first-time contributors and community support re-direction
=> Added issue template

.github/workflows/docker-publish.yml
Adds support for mac in the Github action that updates the docker image
Fixes #
- [ X] The PR does not contain any unnecessary/auto generated code changes.
- [ X] The PR is made from a branch that's **not** called "main" and is up-to-date with "main".
- [ X] The PR is **assigned** to the appropriate reviewers 
@tinkn  Could you please review this when you have a moment? Thank you!
=> add multi-platform support to github action for docker image

CONTRIBUTING.md
This pull request adds a comprehensive contribution guide to the repository. It provides detailed instructions on how to contribute, including steps for setting up the development environment, working on issues, submitting pull requests, and keeping forks in sync with the main repository.
Fixes #273 
@anandwana001  Could you please review this when you have a moment? Thank you!
=> Create CONTRIBUTING.md Fix #273

README.md
Fixes #296 
Added a section for Contributions and linked `CONTRIBUTING.md`, also added it to Table of contents
@anandwana001 Could you please review this when you have a moment? Thank you!
=> feat(docs): added a section for contributions

src/api/auth/mod.rs, src/api/mod.rs, src/api/rbac/controller.rs, src/api/rbac/dtos.rs, src/api/rbac/mod.rs, src/api/vectordb/collections/controller.rs, src/api/vectordb/collections/dtos.rs, src/api/vectordb/collections/mod.rs, src/api/vectordb/collections/repo.rs, src/api/vectordb/collections/service.rs, src/api/vectordb/indexes/mod.rs, src/api/vectordb/search/mod.rs, src/api/vectordb/sync_transaction/mod.rs, src/api/vectordb/sync_transaction/repo.rs, src/api/vectordb/transactions/mod.rs, src/api/vectordb/vectors/mod.rs, src/api/vectordb/versions/mod.rs, src/app_context.rs, src/lib.rs, src/main.rs, src/models/indexing_manager.rs, src/models/types.rs, src/rbac/guards.rs, src/rbac/middleware.rs, src/rbac/mod.rs, src/rbac/store.rs, src/web_server.rs, tests/test-dataset.py, tests/test-grpc.py
This PR implements Role-Based Access Control (RBAC).
-   Introduced RBAC system: `User`, `Role`, `Permission` entities, `RbacStore` (LMDB), `AuthorizationMiddleware`, and guards.
-   Secured all `/vectordb` data plane APIs with RBAC guards.
-   Added new `/rbac` API for RBAC management (users, roles, assignments).
-   Updated user management for consistency between RBAC and authentication.
*   [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".) *(N/A - New feature implementation)*
*   [X] The PR does not contain any unnecessary/auto generated code changes.
*   [X] The PR is made from a branch that's not called "main" and is up-to-date with "main".
*   [ ] The PR is assigned to the …
=> Implement RBAC feature

src/vector_store.rs
fixes node prop serialization with correct IDs
=> fix(hnsw): re-serialize prop for replica nodes (different ID)

src/distance/hamming.rs
- Implements complete Hamming distance functionality for UnsignedByte, SubByte, and HalfPrecisionFP storage types
- Adds robust error handling with length validation and bounds checking
- Supports variable resolution SubByte storage with proper bit manipulation
- **UnsignedByte**: XOR operations on byte values with bit counting
- **SubByte**: Variable resolution bit-packing with masking and shift operations
- **HalfPrecisionFP**: Operates on raw bit representation of f16 values
This addresses the Hamming distance feature from the [Cosdata
roadmap](https://www.cosdata.io/tech/roadmap#:~:text=Hamming-,Todo,-MVP/ALPHA).
Generated by experimental coding agent running on Domain Aligned AI by [Nugen](https://nugen.in) 🚀
=> feat: implemented Hamming distance metrics for all storage types

src/api/vectordb/collections/error.rs, src/api/vectordb/vectors/repo.rs, src/models/prob_node.rs, src/models/serializer/quotients_map.rs, src/models/serializer/tree_map.rs, src/models/serializer/versioned_item.rs, src/models/sparse_ann_query.rs, src/models/tree_map.rs
This PR fixes potential segfaults, due to the value (`T`) obtained from `RwLock<T>` living longer than the `RwLockReadGuard<T>`.
This PR also fixes a deadlock in `LatestNode`.
=> Fix deadlock and potential segfaults

src/api/openapi.rs, src/api/vectordb/collections/controller.rs, src/api/vectordb/collections/dtos.rs, src/api/vectordb/collections/mod.rs, src/api/vectordb/collections/repo.rs, src/api/vectordb/collections/service.rs
Fixes #338 
@tinkn  Could you please review this when you have a moment? Thank you!
=> Fixes #338 : Remove redundant `/collections/list` endpoint and related code

src/api/vectordb/collections/controller.rs, src/api/vectordb/collections/dtos.rs, src/api/vectordb/collections/service.rs, src/api/vectordb/versions/service.rs
=> fix #330: replace hardcoded vector counts

tests/pyproject.toml, tests/test-dataset.py, tests/test-performance.py, tests/test-tf-idf-bm25.py, tests/test-tf-idf-ndcg.py, tests/test.py, tests/test_metadata_filters.py, tests/utils.py, tests/uv.lock
This PR does the following :-
- Because of #357, `poll_completion` was incorrectly invoked on the `txn_id` (a String) instead of the `txn` object (an instance of the Transaction class). This PR corrects the call and resolves the resulting issues.
- Reintroduces `utils.py` just because `test-metadata-filtering.py` uses it and refactoring this test to exclusively use the SDK has been postponed (for now) since its quite tedious.
- Updates the dependency, `cosdata-sdk` to `0.2.5` 
@tinkn  Could you please review this when you have a moment? Thank you!
=> fix(#357): call `poll_completion` on objects of Transaction class, reintroduces `utils.py`

src/indexes/hnsw/mod.rs, tests/test-dataset.py
- feat(hnsw): extend value sampling with finer thresholds
- fix `test-dataset.py` to use less memory
=> Minor patches

tests/test-dataset-streaming.py, tests/test-dataset.py, tests/test-performance.py, tests/uv.lock
This PR significantly enhances the vector dataset processing infrastructure by adding vector normalization for improved similarity calculations and implementing a robust chunked streaming system that can handle large-scale datasets efficiently.
- **Vector Normalization**: Added L2 normalization to all vectors before processing to ensure accurate cosine distance calculations
- **Dataset Configuration Fix**: Corrected the `million-text-embeddings` dataset configuration to properly use the "id" field
- **Memory-Efficient Streaming**: Implemented chunked processing (200k vectors per chunk) to handle datasets that exceed memory limits
- **Scalable Architecture**: Replaced monolithic dataset loading with streaming approach that processes data in manageable batches
- **Smart Memory Management**: …
=> fix: add vector normalization and enhance dataset streaming with chunking and transaction management
